name: Validator of Symbiotic metadata repositories
description: Validates pull requests in Symbiotic metadata repositories
author: Symbiotic

# Define your inputs here.
inputs:
  files:
    description: List of files to validate
    required: true
  issue:
    description: The issue number to comment on (github.context.issue.number)
    required: true
  token:
    description: GITHUB_TOKEN for commenting on the issue
    required: true
  chain-id:
    description: Blockchain chain ID to use for on-chain validation
    required: false
  rpc-url:
    description: Blockchain RPC URL to use for on-chain validation
    required: false

# Define your outputs here.
outputs:
  error:
    description: Validation error

runs:
  using: node20
  main: dist/index.js