name: Validator of Symbiotic metadata repositories
description: Validates pull requests in Symbiotic metadata repositories
author: Symbiotic

# Define your inputs here.
inputs:
  files:
    description: List of files to validate
    required: true
  issue:
    description: The issue number to comment on (github.context.issue.number)
    required: true
  token:
    description: GITHUB_TOKEN for commenting on the issue
    required: true
  vault-registry:
    description: Vaults registry contract address to use for off-chain validation
    required: true
  operator-registry:
    description: Operators registry contract address to use for off-chain validation
    required: true
  network-registry:
    description: Networks registry contract address to use for off-chain validation
    required: true
  chain-id:
    description: Blockchain chain ID to use for on-chain validation
    required: true
  rpc-url:
    description: Blockchain RPC URL to use for on-chain validation
    required: false
  upstream-checkout-path:
    description: Path to the upstream repository checkout folder
    required: false
  rewards-factory:
    description: Rewards factory contract address to use for rewards validation
    required: false

# Define your outputs here.
outputs:
  error:
    description: Validation error

runs:
  using: node24
  main: dist/index.js