name: Validator of Symbiotic metadata repositories
description: Validates pull requests in Symbiotic metadata repositories
author: Symbiotic

# Define your inputs here.
inputs:
  script:
    description: Script to run. Options - validate-metadata, validate-logo, validate-fs
    required: true
  files:
    description: List of files to validate
    required: true

# Define your outputs here.
outputs:
  error:
    description: Validation error

runs:
  using: node20
  main: dist/index.js