name: Get full info
on:
  workflow_call:

jobs:
  generate:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      contents:  write

    steps:
      - name: Checkout repository to get info from
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # pin@v7.0.0

      - name: Checkout metadata-validation-scripts
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # pin@v7.0.0
        with:
          repository: symbioticfi/metadata-validation-scripts
          path: metadata-validation-scripts

      - name: Set up Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238  # pin@v6.2.0
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install tsx @actions/core @actions/github

      - name: Generate
        run: npx tsx metadata-validation-scripts/.github/workflows/scripts/extract-metadata.ts

      - name: Release latest full info
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228  # pin@v3.0.2
        with:
          name: latest
          tag_name: latest
          files: full-info.json
          fail_on_unmatched_files: true

      # Sleep to be sure release is updated in GH CDN before triggering a webhook
      - name: Sleep for 30 seconds
        run: sleep 30s
